name: Node.js CICD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=7168" # Increase to 7 GB

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update NPM
        run: npm i -g npm
      # - name: Install bun
      #   run: npm i --location=global bun
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: touch .env && npm test

  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=7168" # Increase to 7 GB

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update NPM
        run: npm i -g npm
      # - name: Install bun
      #   run: npm i --location=global bun
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
